name: Dice3D
options:
  bundleIdPrefix: com.example
  generateEmptyDirectories: true
  deploymentTarget:
    iOS: "10.0"
targets:
  Dice3D:
    type: application
    platform: iOS
    sources:
      - path: Dice3D
        excludes:
          - "Assets/*.sketch"
    settings:
      base:
        SWIFT_VERSION: 5.0